### ISSUE TITLE
enhancement idea: add tags to tasks, and set difficulty when creating tasks

### ISSUE THREAD

**Issue by pancho-villa** [ASMfreaK/habitipy#12]
Great module! I just found it and it works great on python3.7, unlike the original habitica. I didn't see a mechanism to add a task or set difficulty of the tasks in the todos add command. Is there support for that, or planned in the future?

Thanks!

**Comment by ASMfreaK** [comment]
> Great module! I just found it and it works great on python3.7, unlike the original habitica.

Thanks!

> I didn't see a mechanism to add a task or set difficulty of the tasks in the todos add command. Is there support for that, or planned in the future?

```
$ habitipy todos add --help 
habitipy todos add 0.3.0

Add a todo <todo>

Usage:
    habitipy todos add [SWITCHES] todo...

Meta-switches:
    -h, --help                                         Prints this help message and quits
    --help-all                                         Prints help messages of all sub-commands and quits
    --version                                          Prints the program's version and quits

Switches:
    -c, --config CONFIG:path                           Use file CONFIG for config; the default is
                                                       ~/.config/habitipy/config
    -p, --priority VALUE:{'0.1', '1', '1.5', '2'}      Priority (complexity) of a todo; the default is 1
    -s, --silent                                       Make program more silent; may be given multiple
                                                       times; excludes -v, --verbose
    -v, --verbose                                      Verbose output - log everything.; excludes -s,
                                                       --silent

```

See `-p` flag. There is currently no support for tags, but they can be easily implemented by adding another switch to respective commands, see them [in code](https://github.com/ASMfreaK/habitipy/blob/master/habitipy/cli.py#L616). I'm currently a bit overwhelmed with other tasks tasks.
