### ISSUE TITLE
Optional parameter not optional in habitipy

### ISSUE THREAD

**Issue by tr4nt0r** [ASMfreaK/habitipy#25]
When working on the Home Assistant Habitica integration i noticed the method for fetching the users tasks `api.tasks.user.get(type=task_type)` takes the parameter `type` as mandatory though for the habitica api it is optional. HA uses habitipy v. 0.2.0 but I updated to 0.3.0 and this was still an issue. Could you maybe take a look into this?

**Comment by ASMfreaK** [comment]
It is not "optional" in apidoc in habitica. It is stated in description, . I'll try and fix it in Habitica itself, and create a hotfix here.

**Comment by tr4nt0r** [comment]
Thanks for the quick fix, already tested it and works like a charm. Now i can reduce the number of api call for tasks to 1 instead of 4 :)
